baseURL = 'https://hugh-zhan9.github.io/'
languageCode = 'zh-cn'
title = '牧己'
theme = 'archie'
[params]
	mode="toggle"
	useCDN=false

[[params.social]]
name = "Running"
icon = "battery-charging"
url = "https://running.zhangyk.space"

[[params.social]]
name = "Jellyfin"
icon = "film"
url = "https://ipv4.zhangyk.space:8096"

[[params.social]]
name = "Image"
icon = "image"
url = "https://ipv4.zhangyk.space:9089"

<<<<<<< HEAD
=======
[[params.social]]
name = "PengYouQuan"
icon = "aperture"
url = "https://ipv4.zhangyk.space:3000"

>>>>>>> e12cedad996208e570efe4805ddea58e1bd3c86a
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
