baseURL = 'https://hugh-zhan9.github.io/'
languageCode = 'zh-cn'
title = '牧己'
theme = 'archie'
enableGitInfo = true
[params]
	mode="toggle"
	useCDN=false
	mainSections = ["posts", "crazy-talk"]
	customCSS = ["css/homepage.css"]
	customJS = ["js/homepage.js"]

[[params.social]]
name = "Running"
icon = "battery-charging"
url = "https://hugh-zhan9.github.io/running/"

[[params.social]]
name = "Jellyfin"
icon = "film"
url = "https://ipv4.zhangyk.space:8096"

[[params.social]]
name = "Image"
icon = "image"
url = "https://ipv4.zhangyk.space:9089"

[[params.social]]
name = "PengYouQuan"
icon = "aperture"
url = "https://ipv4.zhangyk.space:3000"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 2

[[menu.main]]
name = "疯言疯语"
url = "/crazy-talk/"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
