baseURL = 'https://hugh-zhan9.github.io/'
languageCode = 'zh-cn'
title = '牧己'
theme = 'archie'
[params]
	mode="auto"
	useCDN=false
	# subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"

[[params.social]]
name = "Running"
icon = "battery-charging"
url = "https://running.zhangyk.space"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
