baseURL = 'https://hugh-zhan9.github.io/'
languageCode = 'zh-cn'
title = '牧己'
theme = 'archie'
enableGitInfo = true
[params]
	favicon="/favicon.png"
	mode="toggle"
	useCDN=false
	mainSections = ["posts", "crazy-talk"]
	customCSS = ["css/site-tokens.css", "css/appearance-controls.css", "css/skin.css", "css/homepage.css", "css/article.css"]
	customJS = ["js/themetoggle.js", "js/homepage.js"]

[[params.social]]
name = "Running"
icon = "battery-charging"
url = "https://hugh-zhan9.github.io/running/"

[[params.social]]
name = "Jellyfin"
icon = "film"
url = "https://ipv4.zhangyk.space:8096"

[[params.social]]
name = "Image"
icon = "image"
url = "/images/"

[[params.social]]
name = "PengYouQuan"
icon = "aperture"
url = "https://ipv4.zhangyk.space:3000"

[[menu.main]]
name = "首页"
url = "/"
weight = 1

[[menu.main]]
name = "文章"
url = "/blog/"
weight = 2

[[menu.main]]
name = "疯言疯语"
url = "/crazy-talk/"
weight = 3

[[menu.main]]
name = "标签"
url = "/tags"
weight = 4

[[menu.main]]
name = "图床"
url = "/images/"
weight = 5
